# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: step by step 
email: huyongdeshuxue@126.com
description: > # this means to ignore newlines until "baseurl:"
  步步为营，一步一个脚印
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: huyongde 
gems: 
    - jekyll-paginate
    - jekyll-archives
paginate: 5
paginate_path: "/page:num/"

#jekyll-archives:
#  enabled: all 
#  layout: 'page'
#  permalinks:
#    year: '/:year/'
#    month: '/:year/:month/'
#    day: '/:year/:month/:day/'
#    tag: '/tags/:name/'
#    #category: '/category/:name/'

# Build settings
markdown: rdiscount 

